spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books
    username: root
#    password: AJin
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  web:
    resources:
      static-locations: classpath:/static/
  redis:
    host: 106.55.240.132
    port: 6379
    password: 123456
reggie:
  path: D:\xuexi\book\src\main\resources\static
#  path: /opt/static/static
